services:
  - type: web
    name: safechain-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_webhook.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com
    autoDeploy: true 